// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'loginCaptcha': string;
  'loginForm': string;
  'loginFormBody': string;
  'loginFormFooter': string;
  'loginFormWrapper': string;
  'loginSubmit': string;
  'loginTips': string;
  'loginTitle': string;
  'login_captcha': string;
  'login_form': string;
  'login_form_body': string;
  'login_form_footer': string;
  'login_form_wrapper': string;
  'login_submit': string;
  'login_tips': string;
  'login_title': string;
}
export const cssExports: CssExports;
export default cssExports;
